version: '3.8'

volumes:
  elasticsearch:

services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: search
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - 'xpack.security.enabled=false'
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - app-network  
  hari-backend:
    image: hari-backend:latest
    container_name: hari-backend
    build:
      context: backend
    ports:
      - "3000:3000"
    environment:
      - AZURE_OPENAI_API_KEY=CHANGE_ME
      - USE_AZURE=true
      - ELASTIC_SEARCH_HOST_PORT=http://search:9200
    depends_on:
      - search
    networks:
      - app-network
  hari-front:
    image: hari-front:latest
    ports:
      - "8080:80"
    build:
      context: frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge